package cs2365_project3;

import java.util.ArrayList;

/** GUI for the Game
 * @author Chase Willis
 * @version 1.0
 * @return What dice they are going to roll, rerolls, duel, what the user rolled
*/
public class DiceGameGUI extends javax.swing.JFrame {

    private int dieChoice;
    private boolean expansion;
    private String name;
    private ArrayList<Dice> diceArray;
    int[] test = {5,0,0,0}; //default to all white dice
    DiceController diceHandler = new DiceController(test);
    private int rerolls = 3;
    private int arrowCount = 0;
    private Turn turn;
    
    public DiceGameGUI() {
        initComponents();
    }
    
    public void setDieChoice(int choice)
    {
        this.dieChoice = choice;
    }
    
    public int getDieChoice()
    {
        return this.dieChoice;
    }
    
    public void setExpansion(boolean expansion)
    {
        this.expansion = expansion;
    }
    
    public boolean getExpansion()
    {
        return this.expansion;
    }
    
    public void setName(String name)
    {
        this.name = name;
    }
    
    public String getName()
    {
        return this.name;
    }
    
    public void setDiceArray(ArrayList<Dice> diceArray)
    {
        this.diceArray = diceArray;
    }
    
    public ArrayList<Dice> getDiceArray()
    {
        return new ArrayList<>(diceArray);
    }
    
    public void usedReroll()
    {
        this.rerolls--;
    }
    
    public int getReroll()
    {
        return this.rerolls;
    }
    
    public void decreaseArrowCount()
    {
        this.arrowCount--;
    }
    
    public void increaseArrowCount()
    {
        this.arrowCount++;
    }
    
    public int getArrowCount()
    {
        return this.arrowCount;
    }

    public void setTurn(Turn turn)
    {
        this.turn = turn;
    }
    
    public Turn getTurn()
    {
        return this.turn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DieOption = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Die1 = new javax.swing.JTextField();
        Die2 = new javax.swing.JTextField();
        Die3 = new javax.swing.JTextField();
        Die4 = new javax.swing.JTextField();
        Die5 = new javax.swing.JTextField();
        Die6 = new javax.swing.JTextField();
        Die7 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        DiceReroll = new javax.swing.JTextField();
        RerollDice = new javax.swing.JButton();
        DoneWithRolling = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        NumRerolls = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        RollRerolls = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        ArrowsRolled = new javax.swing.JTextField();
        TakeChiefArrow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Bang! Dice Roll"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("White Dice Meanings:");

        jLabel48.setText("Dice Number (1-5) based on the ");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("0 - Arrow");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("1 - Shoot Self");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("2 - Shoot Person One Over Left/Right Double Damage");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("3 - Shoot Person Two Over Left/Right Double Damage");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("4 - Dynamite");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("5 - Gatling Gun Double Damage");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("5 - Gatling Gun");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("0 - Arrow");

        jLabel29.setText("Select one of the options for 5th die: (1-White, 2-Coward, 3-Loudmouth)");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("1 - Dynamite");

        DieOption.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DieOption.setText("1");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("2 - Shoot Person One Over Left/Right");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("3 - Shoot Person Two Over Left/Right");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("4 - Beer");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("5 - Gatling Gun");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Black Dice Meanings:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("0 - Arrow");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("1 - Dynamite");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("2 - Whiskey Bottle");

        Die1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Die1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Die2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Die2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Die2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Die2ActionPerformed(evt);
            }
        });

        Die3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Die3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Die4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Die4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Die5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Die5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Die6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Die6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Die7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Die7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Die7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Die7ActionPerformed(evt);
            }
        });

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("White Die");

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("White Die");

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("White Die");

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Black Die");

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Black Die");

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Coward Die ");

        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Loudmouth Die");

        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("Enter the dice you would like to reroll and press reroll, repeat for all dice you want to reroll.");

        RerollDice.setText("Reroll");
        RerollDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RerollDiceActionPerformed(evt);
            }
        });

        DoneWithRolling.setText("Done");
        DoneWithRolling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneWithRollingActionPerformed(evt);
            }
        });

        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Rerolls Left:");

        NumRerolls.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumRerolls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumRerollsActionPerformed(evt);
            }
        });

        jLabel40.setText("When Done With Rerolls press Done:");

        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("White Die");

        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("White Die");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("3 - Duel Guns");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("4 - Duel Guns");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Coward Die Meanings:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("0 - Arrow");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("1 - Broken Arrow");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("2 - Shoot Person One Over Left/Right");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("3 - Beer");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("4 - Dynamite");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("5 - Double Beer");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Loudmouth Die Meanings:");

        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("order the boxs are filled.");

        jLabel50.setText("When done entering all the dice to reroll press role:");

        RollRerolls.setText("Roll");
        RollRerolls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RollRerollsActionPerformed(evt);
            }
        });

        jLabel30.setText("Number of Arrows rolled:");

        TakeChiefArrow.setText("Chief Arrow");
        TakeChiefArrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TakeChiefArrowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(67, 67, 67)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21))))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(jLabel26)
                            .addComponent(jLabel28))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel40)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Die1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Die2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Die3, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jLabel38))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Die4, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DiceReroll)))
                            .addComponent(jLabel50)
                            .addComponent(jLabel29))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DoneWithRolling, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Die5, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RerollDice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RollRerolls, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Die6, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Die7)
                                    .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NumRerolls))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(ArrowsRolled, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(66, 66, 66))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(TakeChiefArrow)
                                            .addComponent(jLabel30))
                                        .addGap(23, 23, 23))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(DieOption, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addComponent(jLabel15)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(jLabel16)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10)
                    .addComponent(jLabel17)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11)
                    .addComponent(jLabel18)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12)
                    .addComponent(jLabel19)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13)
                    .addComponent(jLabel20)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel21)
                    .addComponent(jLabel28)
                    .addComponent(jLabel14))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(DieOption, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Die1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Die2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Die3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Die4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Die5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Die6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Die7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ArrowsRolled, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel49))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel30)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DiceReroll, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38)
                            .addComponent(RerollDice)
                            .addComponent(jLabel39)
                            .addComponent(NumRerolls, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel50)
                            .addComponent(RollRerolls))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DoneWithRolling)
                            .addComponent(jLabel40)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TakeChiefArrow)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Die2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Die2ActionPerformed
        // TODO add your handling code here:
        // Get dice numbers

    }//GEN-LAST:event_Die2ActionPerformed

    private void Die7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Die7ActionPerformed
        // TODO add your handling code here:
        // Ignore This
    }//GEN-LAST:event_Die7ActionPerformed

    private void RerollDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RerollDiceActionPerformed
        // TODO add your handling code here:
        int DiceToReroll;
        ArrayList<Dice> diceArray = getDiceArray();
        
        DiceToReroll = (int)Float.parseFloat(DiceReroll.getText()); //Dice to Reroll
        
        for(Dice dice : diceArray)
        {
            if((DiceToReroll-1) == dice.getDiceIndex())
                dice.setReroll(true, getName());
        }
        //Die1.setText(String.valueOf()); // Number for die 1 White 1
        //Die2.setText(String.valueOf()); // Number for die 2 White 2
        //Die3.setText(String.valueOf()); // Number for die 3 White 3
        //Die4.setText(String.valueOf()); // Number for die 4 Black 1 or White 4
        //Die5.setText(String.valueOf()); // Number for die 5 Black 2 or White 5
        //Die6.setText(String.valueOf()); // Number for die 6 Coward
        //Die7.setText(String.valueOf()); // Number for die 7 Loudmouth
    }//GEN-LAST:event_RerollDiceActionPerformed

    private void DoneWithRollingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneWithRollingActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_DoneWithRollingActionPerformed

    private void RollRerollsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RollRerollsActionPerformed
        // TODO add your handling code here:
        setDieChoice((int)Float.parseFloat(DieOption.getText()));
        if(getExpansion())
        {
            if(getDieChoice() == 1)
            {
                test[0] = 3;
                test[1] = 2;
            }
            else if(getDieChoice() == 2)
            {
                test[0] = 2;
                test[1] = 2;
                test[2] = 1;
            }
            else if(getDieChoice() == 3)
            {
                test[0] = 2;
                test[1] = 2;
                test[3] = 1;
            }
            
            diceHandler = new DiceController(test);
        }
        
        
        setDiceArray(diceHandler.getDiceArray());
        Turn turn = getTurn();
        if(getReroll() > 0)
        {
            diceHandler.setDiceArray(diceHandler.rollAllDice());
            usedReroll();
            if(diceHandler.checkFrequency("Dynamite") >= 3)
            {
                while(getReroll() > 0)
                    usedReroll();
            }
            if(getExpansion())
            {
                for(Dice dice : diceHandler.getDiceArray())
                {
                    if(name.equals("APACHE KID") && turn.arrow.UseArrow().equals(""))
                        turn.arrow.TakeArrow(name);
                    else if(!name.equals("BILL NOFACE"))
                    {                                
                        if(turn.arrow.UseArrow().equals("") && dice.getDiceString().equals("Arrow"))
                            turn.arrow.TakeArrow(name);
                        else if(dice.getDiceString().equals("Arrow"))
                            turn.indianArrow();
                    }
                }

                for(Dice dice : diceHandler.getDiceArray())
                {
                    if(dice.getDiceString().equals("Broken Arrow"))
                        turn.brokenArrow();
                }

                for(Dice dice : diceHandler.getDiceArray())
                {
                    if(dice.getDiceString().equals("Bullet"))
                        turn.bullet();
                }
            }
            else
            {
                for(Dice dice : diceHandler.getDiceArray())
                {
                    if(dice.getDiceString().equals("Arrow") && !name.equals("BILL NOFACE"))
                        turn.indianArrow();                             
                }
            }
        }
        

        for(Dice dice : diceHandler.getDiceArray())
        {
            if(dice.getDiceString().equals("Arrow") && getReroll() > 0)
                increaseArrowCount();
        }
        
        if(getExpansion())
        {
            if(getDieChoice() == 1) //white die as 5th
            {
                Die1.setText(String.valueOf(diceArray.get(0).getDiceInt())); // Number for die 1 White 1
                Die2.setText(String.valueOf(diceArray.get(1).getDiceInt())); // Number for die 2 White 2
                Die3.setText(String.valueOf(diceArray.get(2).getDiceInt())); // Number for die 3 White 3
                Die4.setText(String.valueOf(diceArray.get(3).getDiceInt())); // Number for die 4 Black 1 or White 4
                Die5.setText(String.valueOf(diceArray.get(4).getDiceInt())); // Number for die 5 Black 2 or White 5
            }
            else if(getDieChoice() == 2) //coward die as 5th
            {
                Die1.setText(String.valueOf(diceArray.get(0).getDiceInt())); // Number for die 1 White 1
                Die2.setText(String.valueOf(diceArray.get(1).getDiceInt())); // Number for die 2 White 2
                Die4.setText(String.valueOf(diceArray.get(2).getDiceInt())); // Number for die 4 Black 1 or White 4
                Die5.setText(String.valueOf(diceArray.get(3).getDiceInt())); // Number for die 5 Black 2 or White 5
                Die6.setText(String.valueOf(diceArray.get(4).getDiceInt())); // Number for die 6 Coward
            }
            else if(getDieChoice() == 3) //loudmouth die as 5th
            {
                Die1.setText(String.valueOf(diceArray.get(0).getDiceInt())); // Number for die 1 White 1
                Die2.setText(String.valueOf(diceArray.get(1).getDiceInt())); // Number for die 2 White 2
                Die4.setText(String.valueOf(diceArray.get(2).getDiceInt())); // Number for die 4 Black 1 or White 4
                Die5.setText(String.valueOf(diceArray.get(3).getDiceInt())); // Number for die 5 Black 2 or White 5
                Die7.setText(String.valueOf(diceArray.get(4).getDiceInt())); // Number for die 7 Loudmouth
            }
        }
        else //all white die
        {
            Die1.setText(String.valueOf(diceArray.get(0).getDiceInt())); // Number for die 1 White 1
            Die2.setText(String.valueOf(diceArray.get(1).getDiceInt())); // Number for die 2 White 2
            Die3.setText(String.valueOf(diceArray.get(2).getDiceInt())); // Number for die 3 White 3
            Die4.setText(String.valueOf(diceArray.get(3).getDiceInt())); // Number for die 4 Black 1 or White 4
            Die5.setText(String.valueOf(diceArray.get(4).getDiceInt())); // Number for die 5 Black 2 or White 5
        }
        
        NumRerolls.setText(String.valueOf(getReroll()));
        ArrowsRolled.setText(String.valueOf(getArrowCount()));

        setDiceArray(diceArray);
               
        
        //Die1.setText(String.valueOf()); // Number for die 1 White 1
        //Die2.setText(String.valueOf()); // Number for die 2 White 2
        //Die3.setText(String.valueOf()); // Number for die 3 White 3
        //Die4.setText(String.valueOf()); // Number for die 4 Black 1 or White 4
        //Die5.setText(String.valueOf()); // Number for die 5 Black 2 or White 5
        //Die6.setText(String.valueOf()); // Number for die 6 Coward
        //Die7.setText(String.valueOf()); // Number for die 7 Loudmouth
    }//GEN-LAST:event_RollRerollsActionPerformed

    private void NumRerollsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumRerollsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumRerollsActionPerformed

    private void TakeChiefArrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TakeChiefArrowActionPerformed
        // TODO add your handling code here:
        Turn turn = getTurn();
        if(turn.arrow.UseArrow().equals(""))
        {
            turn.arrow.TakeArrow(getName());
            decreaseArrowCount();
        }
    }//GEN-LAST:event_TakeChiefArrowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiceGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiceGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiceGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiceGameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiceGameGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ArrowsRolled;
    private javax.swing.JTextField DiceReroll;
    private javax.swing.JTextField Die1;
    private javax.swing.JTextField Die2;
    private javax.swing.JTextField Die3;
    private javax.swing.JTextField Die4;
    private javax.swing.JTextField Die5;
    private javax.swing.JTextField Die6;
    private javax.swing.JTextField Die7;
    private javax.swing.JTextField DieOption;
    private javax.swing.JButton DoneWithRolling;
    private javax.swing.JTextField NumRerolls;
    private javax.swing.JButton RerollDice;
    private javax.swing.JButton RollRerolls;
    private javax.swing.JButton TakeChiefArrow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
