package cs2365_project3;

import java.util.ArrayList;

/** GUI for the Game part of the Game
 * @author Chase Willis
 * @version 1.0
 * Collaborators: Jacob Strickland
*/
public class GameGUI extends javax.swing.JFrame {

    private Game game;
    private boolean gameOver = false;    
    private int index;
    private Turn turn;
    private ArrayList<Player> tableSeating;
    private String output;
    private DiceGameGUI obj;
    private int diceCount = 0;
    private int shootValue;
    private boolean again; //used to handle double shoot and heal
    
    /**
     * Method to initialize game gui.
     */
    public GameGUI() {
        initComponents();
    }
    
    /**
     * Method to set the game 
     * @param game Game, the game to set the game as
     */
    public void setGame(Game game)
    {
        this.game = game;
    }
    
    /**
     * Method to get game set in setGame method
     * @return game
     */
    public Game getGame()
    {
        return this.game;
    }
    
    /**
     * Method to set game over flag, false game is not over
     * @param over boolean
     */
    public void setGameOver(boolean over)
    {
        this.gameOver = over;
    }
    
    /**
     * Method to get whether game is over or not
     * @return gameOver boolean 
     */
    public boolean getGameOver()
    {
        return this.gameOver;
    }
    
    
    public void setIndex(int index)
    {
        this.index = index;
    }
    
    public int getIndex()
    {
        return this.index;
    }
    
    /**
     * Method to set the turn
     * @param turn Turn, the turn to set the turn as
     */
    public void setTurn(Turn turn)
    {
        this.turn = turn;
    }
    
    /**
     * Method to get turn
     * @return turn
     */
    public Turn getTurn()
    {
        return this.turn;
    }
    
    /**
     * Method to set the table seating for the game.
     */
    public void setTableSeating()
    {
        this.tableSeating = getGame().getTableSeating();
    }
    
    /**
     * Method to get the table seating created in setTableSeating method
     * @return tableSeating Arraylist
     */
    public ArrayList<Player> getTableSeating()
    {
        return new ArrayList<>(tableSeating);
    }
    
    /**
     * Method to set the output
     * @param output string
     */
    public void setOutput(String output)
    {
        this.output = output;
    }
    
    /**
     * Method to get the output
     * @return output string
     */
    public String getOutput()
    {
        return this.output;
    }
    
    /**
     * Method to set the dice gui to see roll results in game gui
     * @param obj DiceGameGUI, the gui to set the gui as
     */
    public void setDiceGUI(DiceGameGUI obj)
    {
        this.obj = obj;
    }
    /**
     * Method to get the dice gui
     * @return obj
     */
    public DiceGameGUI getDiceGUI()
    {
        return this.obj;
    }
    
    /**
     * Method to reset the dice count so next player can roll all needed dice.
     */
    public void resetDiceCount()
    {
        this.diceCount = 0;
    }
    
    /**
     * Method to increase the dice count by 1.
     */
    public void increaseDiceCount()
    {
        this.diceCount++;
    }
    
    /**
     * Method to decrease the dice amount by 1.
     */
    public void decreaseDiceCount()
    {
        this.diceCount++;
    }
    
    /**
     * Method to return the dice count
     * @return diceCount integer
     */
    public int getDiceCount()
    {
        return this.diceCount;
    }
    
    /**
     * Method to set the shoot value for when shoot is rolled 
     * @param value integer
     */
    public void setShootValue(int value)
    {
        this.shootValue = value;
    }
    
    /**
     * Method to return the shoot value
     * @return shootValue integer 
     */
    public int getShootValue()
    {
        return this.shootValue;
    }
    
    /**
     * Method that will set value for repeating an action.
     * @param set Boolean, true if repeat action
     */
    public void setAgain(boolean set)
    {
        this.again = set;
    }
    
    /**
     * Method that will get value for repeating an action
     * @return Boolean, true if repeat action
     */
    public boolean getAgain()
    {
        return this.again;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Player6Zombie = new javax.swing.JTextField();
        Player4Roll = new javax.swing.JTextField();
        Player4Zombie = new javax.swing.JTextField();
        Player5Char = new javax.swing.JTextField();
        Player5Health = new javax.swing.JTextField();
        Player5Arrow = new javax.swing.JTextField();
        Player5Roll = new javax.swing.JTextField();
        Player5Zombie = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        Player1Zombie = new javax.swing.JTextField();
        ArrowPile = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Player2Char = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Player2Health = new javax.swing.JTextField();
        CardPile = new javax.swing.JTextField();
        Player2Arrow = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Player2Roll = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Player2Zombie = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Player3Char = new javax.swing.JTextField();
        Player3Health = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Player1Char = new javax.swing.JTextField();
        Player1Health = new javax.swing.JTextField();
        Player1Arrow = new javax.swing.JTextField();
        Player1Roll = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Player3Arrow = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Player3Roll = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        Player3Zombie = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Player8Char = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        Player8Health = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        Player8Arrow = new javax.swing.JTextField();
        Player8Roll = new javax.swing.JTextField();
        Player8Zombie = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Player7Char = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        Player7Health = new javax.swing.JTextField();
        NextTurn = new javax.swing.JButton();
        Player7Arrow = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        Player7Roll = new javax.swing.JTextField();
        Player7Zombie = new javax.swing.JTextField();
        Player4Char = new javax.swing.JTextField();
        WhoToShoot = new javax.swing.JTextField();
        Player6Char = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Player6Health = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        ShootPerson = new javax.swing.JTextField();
        WhoToHeal = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        Player4Health = new javax.swing.JTextField();
        HealPerson = new javax.swing.JTextField();
        Player6Arrow = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        Player4Arrow = new javax.swing.JTextField();
        IndianChiefArrow = new javax.swing.JTextField();
        Player6Roll = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        Resolve = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        healChoice = new javax.swing.JButton();
        ShootChoice = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Bang! The Dice Game"));

        Player6Zombie.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Player4Roll.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Player4Zombie.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Player5Char.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Player5Health.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Player5Arrow.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Player5Roll.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Player5Zombie.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Player1Zombie.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ArrowPile.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setText("Player 2");

        jLabel9.setText("Arrow Pile");

        Player2Char.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel10.setText("Card Pile");

        Player2Health.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        CardPile.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Player2Arrow.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel11.setText("Health");

        Player2Roll.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel12.setText("Arrow");

        Player2Zombie.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setText("Player 3");

        Player3Char.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Player3Health.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setText("Player 1");

        Player1Char.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Player1Health.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Player1Arrow.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Player1Roll.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel13.setText("Health");

        jLabel14.setText("Health");

        jLabel15.setText("Health");

        jLabel16.setText("Health");

        Player3Arrow.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel17.setText("Health");

        Player3Roll.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel18.setText("Health");

        Player3Zombie.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel19.setText("Health");

        jLabel4.setText("Player 8");

        jLabel20.setText("Arrow");

        Player8Char.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel21.setText("Arrow");

        Player8Health.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel22.setText("Arrow");

        Player8Arrow.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Player8Roll.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Player8Zombie.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setText("Player 7");

        jLabel23.setText("Arrow");

        jLabel24.setText("Arrow");

        jLabel25.setText("Arrow");

        jLabel26.setText("Arrow");

        Player7Char.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel27.setText("Shooting");

        Player7Health.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        NextTurn.setText("Next Turn");
        NextTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextTurnActionPerformed(evt);
            }
        });

        Player7Arrow.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel28.setText("Healing");

        Player7Roll.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Player7Zombie.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Player4Char.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        WhoToShoot.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Player6Char.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setText("Player 6");

        jLabel7.setText("Player 4");

        Player6Health.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel29.setText("Shoot:");

        ShootPerson.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ShootPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShootPersonActionPerformed(evt);
            }
        });

        WhoToHeal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel30.setText("Heal:");

        Player4Health.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        HealPerson.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Player6Arrow.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel31.setText("Indian Chief Arrow");

        Player4Arrow.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        IndianChiefArrow.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Player6Roll.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel32.setText("Player 5");

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Held by:");

        Resolve.setText("Resolve");
        Resolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResolveActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        healChoice.setText("Choice");
        healChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                healChoiceActionPerformed(evt);
            }
        });

        ShootChoice.setText("Choice");
        ShootChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShootChoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Player7Char, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Player7Zombie, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel25))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Player7Health, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Player7Arrow, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Player7Roll, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Player3Char, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Player3Health, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Player3Arrow, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Player3Roll, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Player3Zombie)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel32)
                        .addGap(109, 109, 109)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(Player4Char, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(141, 141, 141))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IndianChiefArrow, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel31))))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel17)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Player6Health, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(Player6Char)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel24)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Player6Arrow, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(Player6Roll)
                                        .addComponent(Player6Zombie, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(CardPile, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jLabel10)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Player4Health, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Player4Arrow, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Player4Roll, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Player4Zombie))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(NextTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Update, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Resolve, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Player2Zombie, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Player2Roll, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Player2Health, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Player2Arrow, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(88, 88, 88)
                                        .addComponent(jLabel3)
                                        .addGap(14, 14, 14))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(ArrowPile, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(132, 132, 132))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(141, 141, 141)))))))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(171, 171, 171))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(WhoToShoot, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jLabel27))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ShootPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ShootChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Player1Health, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Player1Char, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(24, 24, 24))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Player5Zombie, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Player5Roll, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(104, 104, 104)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Player1Arrow, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Player1Roll, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Player8Roll, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player8Zombie, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel26)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Player8Arrow, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Player8Health, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(Player8Char, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(82, 82, 82)
                                        .addComponent(Player1Zombie, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel23)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Player5Arrow, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Player5Health, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(Player5Char, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Player2Char, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(24, 24, 24)))
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(WhoToHeal, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(healChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HealPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Player1Char, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Player1Health, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Player1Arrow, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Player1Roll, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Player1Zombie, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Player2Char, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Player8Char, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Player2Health, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Player8Health, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Player2Arrow, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Player8Arrow, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Player2Roll, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player8Roll, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(WhoToShoot, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel29)
                                    .addComponent(ShootPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ShootChoice)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(WhoToHeal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel30)
                                    .addComponent(HealPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(healChoice))))
                        .addGap(174, 174, 174)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Player2Zombie, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player8Zombie, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Player3Char, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Player7Char, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Player3Health, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Player7Health, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel18)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Player3Arrow, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Player7Arrow, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel25)
                            .addComponent(ArrowPile, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CardPile, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Player3Roll, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Player7Roll, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Player3Zombie, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Player7Zombie, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Player4Char, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Player6Char, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Player6Health, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Player4Health, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17)
                                .addComponent(jLabel16)
                                .addComponent(jLabel31)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Player6Arrow, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player4Arrow, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel24)
                                    .addComponent(Player5Char, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Player6Roll, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player4Roll, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(Player5Health, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IndianChiefArrow, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Player6Zombie, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Player4Zombie, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(Player5Arrow, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Update)
                        .addGap(11, 11, 11)
                        .addComponent(NextTurn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Resolve)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Player5Roll, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Player5Zombie, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method that will update the gui when button pressed.
     */
    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here: // Button is used to update all the players variables
        setTableSeating();
        ArrayList<Player> tableSeating = getTableSeating();
        
        if(getGame().getTableSeating().size() < 1)
        {
            Player1Char.setText(""); //How to Enter a number into the jTextField1 (Replace with string)
            Player1Health.setText(""); //Health of players
            Player1Arrow.setText(""); //Number of Arrow of players
            Player1Roll.setText(""); //Player's roll when dead or Sheirff
            Player1Zombie.setText(""); //If Player is a zombie
        }
        else
        {
            Player1Char.setText(tableSeating.get(0).getCharacterName()); //How to Enter a number into the jTextField1 (Replace with string)
            Player1Health.setText(String.valueOf(tableSeating.get(0).getHealth())); //Health of players
            Player1Arrow.setText(String.valueOf(tableSeating.get(0).getArrowCount())); //Number of Arrow of players
            if(tableSeating.get(0).getUser() || tableSeating.get(0).getRole().equals("Sheriff") || tableSeating.get(0).getRole().equals("Alive") 
                    || tableSeating.get(0).getRole().equals("Zombie") || tableSeating.get(0).getRole().equals("Zombie Master"))
                Player1Roll.setText(tableSeating.get(0).getRole()); //Player's roll when dead or Sheirff
            else
                Player1Roll.setText(""); //Player's roll when dead or Sheirff
            Player1Zombie.setText(tableSeating.get(0).getAbility()); //If Player is a zombie
        }
        
        if(getGame().getTableSeating().size() < 2)
        {
            Player2Char.setText(""); //How to Enter a number into the jTextField1 (Replace with string)
            Player2Health.setText(""); //Health of players
            Player2Arrow.setText(""); //Number of Arrow of players
            Player2Roll.setText(""); //Player's roll when dead or Sheirff
            Player2Zombie.setText(""); //If Player is a zombie
        }
        else
        {
            Player2Char.setText(tableSeating.get(1).getCharacterName()); //How to Enter a number into the jTextField1 (Replace with string)
            Player2Health.setText(String.valueOf(tableSeating.get(1).getHealth())); //Health of players
            Player2Arrow.setText(String.valueOf(tableSeating.get(1).getArrowCount())); //Number of Arrow of players
            if(tableSeating.get(1).getUser() || tableSeating.get(1).getRole().equals("Sheriff") || tableSeating.get(1).getRole().equals("Alive") 
                    || tableSeating.get(1).getRole().equals("Zombie") || tableSeating.get(1).getRole().equals("Zombie Master"))
                Player2Roll.setText(tableSeating.get(1).getRole()); //Player's roll when dead or Sheirff
            else
                Player2Roll.setText(""); //Player's roll when dead or Sheirff
            Player2Zombie.setText(tableSeating.get(1).getAbility()); //If Player is a zombie
        }
        
        if(getGame().getTableSeating().size() < 3)
        {
            Player3Char.setText(""); //How to Enter a number into the jTextField1 (Replace with string)
            Player3Health.setText(""); //Health of players
            Player3Arrow.setText(""); //Number of Arrow of players
            Player3Roll.setText(""); //Player's roll when dead or Sheirff
            Player3Zombie.setText(""); //If Player is a zombie
        }
        else
        {
            Player3Char.setText(tableSeating.get(2).getCharacterName()); //How to Enter a number into the jTextField1 (Replace with string)
            Player3Health.setText(String.valueOf(tableSeating.get(2).getHealth())); //Health of players
            Player3Arrow.setText(String.valueOf(tableSeating.get(2).getArrowCount())); //Number of Arrow of players
            if(tableSeating.get(2).getUser() || tableSeating.get(2).getRole().equals("Sheriff") || tableSeating.get(2).getRole().equals("Alive") 
                    || tableSeating.get(2).getRole().equals("Zombie") || tableSeating.get(2).getRole().equals("Zombie Master"))
                Player3Roll.setText(tableSeating.get(2).getRole()); //Player's roll when dead or Sheirff
            else
                Player3Roll.setText(""); //Player's roll when dead or Sheirff
            Player3Zombie.setText(tableSeating.get(2).getAbility()); //If Player is a zombie
        }
        
        if(getGame().getTableSeating().size() < 4)
        {
            Player4Char.setText(""); //How to Enter a number into the jTextField1 (Replace with string)
            Player4Health.setText(""); //Health of players
            Player4Arrow.setText(""); //Number of Arrow of players
            Player4Roll.setText(""); //Player's roll when dead or Sheirff
            Player4Zombie.setText(""); //If Player is a zombie
        }
        else
        {
            Player4Char.setText(tableSeating.get(3).getCharacterName()); //How to Enter a number into the jTextField1 (Replace with string)
            Player4Health.setText(String.valueOf(tableSeating.get(3).getHealth())); //Health of players
            Player4Arrow.setText(String.valueOf(tableSeating.get(3).getArrowCount())); //Number of Arrow of players
            if(tableSeating.get(3).getUser() || tableSeating.get(3).getRole().equals("Sheriff") || tableSeating.get(3).getRole().equals("Alive") 
                    || tableSeating.get(3).getRole().equals("Zombie") || tableSeating.get(3).getRole().equals("Zombie Master"))
                Player4Roll.setText(tableSeating.get(3).getRole()); //Player's roll when dead or Sheirff
            else
                Player4Roll.setText(""); //Player's roll when dead or Sheirff
            Player4Zombie.setText(tableSeating.get(3).getAbility()); //If Player is a zombie
        }
        
        if(getGame().getTotalPlayers() >=  5)
        {
            if(getGame().getTableSeating().size() < 5)
            {
                Player5Char.setText(""); //How to Enter a number into the jTextField1 (Replace with string)
                Player5Health.setText(""); //Health of players
                Player5Arrow.setText(""); //Number of Arrow of players
                Player5Roll.setText(""); //Player's roll when dead or Sheirff
                Player5Zombie.setText(""); //If Player is a zombie
            }
            else
            {
                Player5Char.setText(tableSeating.get(4).getCharacterName()); //How to Enter a number into the jTextField1 (Replace with string)
                Player5Health.setText(String.valueOf(tableSeating.get(4).getHealth())); //Health of players
                Player5Arrow.setText(String.valueOf(tableSeating.get(4).getArrowCount())); //Number of Arrow of players
                if(tableSeating.get(4).getUser() || tableSeating.get(4).getRole().equals("Sheriff") || tableSeating.get(4).getRole().equals("Alive") 
                        || tableSeating.get(4).getRole().equals("Zombie") || tableSeating.get(4).getRole().equals("Zombie Master"))
                    Player5Roll.setText(tableSeating.get(4).getRole()); //Player's roll when dead or Sheirff
                else
                    Player5Roll.setText(""); //Player's roll when dead or Sheirff
                Player5Zombie.setText(tableSeating.get(4).getAbility()); //If Player is a zombie
            }
        }
        
        if(getGame().getTotalPlayers() >=  6)
        {
            if(getGame().getTableSeating().size() < 6) //if player died, clear space
            {
                Player6Char.setText(""); //How to Enter a number into the jTextField1 (Replace with string)
                Player6Health.setText(""); //Health of players
                Player6Arrow.setText(""); //Number of Arrow of players
                Player6Roll.setText(""); //Player's roll when dead or Sheirff
                Player6Zombie.setText(""); //If Player is a zombie
            }
            else
            {
                Player6Char.setText(tableSeating.get(5).getCharacterName()); //How to Enter a number into the jTextField1 (Replace with string)
                Player6Health.setText(String.valueOf(tableSeating.get(5).getHealth())); //Health of players
                Player6Arrow.setText(String.valueOf(tableSeating.get(5).getArrowCount())); //Number of Arrow of players
                if(tableSeating.get(5).getUser() || tableSeating.get(5).getRole().equals("Sheriff") || tableSeating.get(5).getRole().equals("Alive") 
                        || tableSeating.get(5).getRole().equals("Zombie") || tableSeating.get(5).getRole().equals("Zombie Master"))
                    Player6Roll.setText(tableSeating.get(5).getRole()); //Player's roll when dead or Sheirff
                else
                    Player6Roll.setText(""); //Player's roll when dead or Sheirff
                Player6Zombie.setText(tableSeating.get(5).getAbility()); //If Player is a zombie
            }
        }
        
        if(getGame().getTotalPlayers() >=  7)
        {
            if(getGame().getTableSeating().size() < 7) //if player died, clear space
            {
                Player7Char.setText(""); //How to Enter a number into the jTextField1 (Replace with string)
                Player7Health.setText(""); //Health of players
                Player7Arrow.setText(""); //Number of Arrow of players
                Player7Roll.setText(""); //Player's roll when dead or Sheirff
                Player7Zombie.setText(""); //If Player is a zombie
            }
            else
            {
                Player7Char.setText(tableSeating.get(6).getCharacterName()); //How to Enter a number into the jTextField1 (Replace with string)
                Player7Health.setText(String.valueOf(tableSeating.get(6).getHealth())); //Health of players
                Player7Arrow.setText(String.valueOf(tableSeating.get(6).getArrowCount())); //Number of Arrow of players
                if(tableSeating.get(6).getUser() || tableSeating.get(6).getRole().equals("Sheriff") || tableSeating.get(6).getRole().equals("Alive") 
                        || tableSeating.get(6).getRole().equals("Zombie") || tableSeating.get(6).getRole().equals("Zombie Master"))
                    Player7Roll.setText(tableSeating.get(6).getRole()); //Player's roll when dead or Sheirff
                else
                    Player7Roll.setText(""); //Player's roll when dead or Sheirff
                Player7Zombie.setText(tableSeating.get(6).getAbility()); //If Player is a zombie
            }
        }
        
        if(getGame().getTotalPlayers() >=  8)
        {
            if(getGame().getTableSeating().size() < 8) //if player died, clear space
            {
                Player8Char.setText(""); //How to Enter a number into the jTextField1 (Replace with string)
                Player8Health.setText(""); //Health of players
                Player8Arrow.setText(""); //Number of Arrow of players
                Player8Roll.setText(""); //Player's roll when dead or Sheirff
                Player8Zombie.setText(""); //If Player is a zombie
            }
            else
            {
                Player8Char.setText(tableSeating.get(7).getCharacterName()); //How to Enter a number into the jTextField1 (Replace with string)
                Player8Health.setText(String.valueOf(tableSeating.get(7).getHealth())); //Health of players
                Player8Arrow.setText(String.valueOf(tableSeating.get(7).getArrowCount())); //Number of Arrow of players
                if(tableSeating.get(7).getUser() || tableSeating.get(7).getRole().equals("Sheriff") || tableSeating.get(7).getRole().equals("Alive") 
                        || tableSeating.get(7).getRole().equals("Zombie") || tableSeating.get(7).getRole().equals("Zombie Master"))
                    Player8Roll.setText(tableSeating.get(7).getRole()); //Player's roll when dead or Sheirff
                else
                    Player8Roll.setText(""); //Player's roll when dead or Sheirff
                Player8Zombie.setText(tableSeating.get(7).getAbility()); //If Player is a zombie
            }
        }

        ArrowPile.setText(String.valueOf(getGame().getArrowPile()));
        CardPile.setText(String.valueOf(getGame().getCardPile()));
        if(getGame().getExpansion())
            IndianChiefArrow.setText(getGame().arrow.UseArrow()); //Send the name of holder of the indian chief arrow

        jTextArea1.setText(getOutput()); //To get the Events of the last turn
    }//GEN-LAST:event_UpdateActionPerformed

    /**
     * Method that will cause the next turn to take place when the button is pressed.
     */
    private void NextTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextTurnActionPerformed
        // TODO add your handling code here:
        if(!getGameOver())
        {
            setTurn(getGame().createTurn(getIndex()));
            if(getGame().getTableSeating().get(getIndex()).getUser())
            {
                resetDiceCount();
                DiceGameGUI obj = new DiceGameGUI(); //This will show the DiceGameGUI
                //pass through the values needed to the gui
                obj.setExpansion(getGame().getExpansion());
                obj.setName(getTurn().getTableSeating().get(getIndex()).getCharacterName());
                obj.setTurn(turn);
                obj.setVisible(true);
                setDiceGUI(obj);
            }
            else                
                getTurn().AIDiceRoll(); //call the turn function to automate a turn
            getTurn().resolveDice(); //resolve the dice from the turn that just occured
            setGameOver(getTurn().getGameOver());
            setGame(getGame().updateGame(getTurn()));
            if(getGame().getExpansion() && !getGame().getDoA() && !getGameOver()) //dead people draw at end of turn
                getGame().deadDraw();
            String output = "";
            if(getGameOver())
            {
                if(gameOver)
                {
                    output = output + "Game over on condition ";
                    //System.out.print("Game over on condition ");
                    switch(getTurn().getWinCond())
                    {
                        case 1: 
                            output = output + "Everybody else died, single Renegade wins.";
                            //System.out.println("Everybody else died, single Renegade wins.");
                            break;
                        case 2: 
                            output = output + "Outlaw and Renegade(s) died, Sheriff and Deputy wins.";
                            //System.out.println("Outlaw and Renegade(s) died, Sheriff and Deputy wins.");
                            break;
                        case 3: 
                            output = output + "Sheriff died, Outlaws win.";
                            //System.out.println("Sheriff died, Outlaws win.");
                            break;
                        case 4: 
                            output = output + "Alive died, Zombies win.";
                            //System.out.println("Alive died, Zombies win.");
                            break;
                        case 5: 
                            output = output + "Zombies died, Alive win.";
                            //System.out.println("Zombies died, Alive win.");
                            break;
                    }
                }
            }
            
            setIndex(getGame().getIndex()); //set index to next player
            setOutput(getTurn().getOutput()); //update the string for what occured
            //getGame().printGameStatus();
        }
        if(getGameOver())
        {
            setOutput(output);
            jTextArea1.setText(getOutput());
        }
            //System.exit(0); //used to go to the next players turn
    }//GEN-LAST:event_NextTurnActionPerformed

    /**
     * Method that will allow the player to resolve their dice roll when the button is pressed.
     */
    private void ResolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResolveActionPerformed
        // TODO add your handling code here:
        String output = "";
        Turn turn = getTurn();
        DiceGameGUI obj = getDiceGUI();
        int c = 1;
        for(Dice dice: obj.getDiceArray()) //print out the dice the user rolled
        {
            output = output + c + ": " + dice.getDiceString() + "\n";
            c++;
        }
        
        output = output + "Currently resolving dice " + (getDiceCount()+1);
        int[] test = {5,0,0,0};
        DiceController diceHandler = new DiceController(test);
        diceHandler.setDiceArray(obj.getDiceArray());
        ArrayList<Player> player = turn.getTableSeating();
        int currentPlayer = turn.getIndex();

        String name = turn.getName();
        turn.setGUI(this);
        int diceCount = getDiceCount();
        
        if(diceCount == 0) //things to check only once on the first go around
        {
            //resolve the dice in correct order, arrows are already handled as they are rolled
            if(diceHandler.checkFrequency("Dynamite") >= 3)
            {
                player.get(currentPlayer).TakeDamage(1);
                //System.out.println("Dynamite! Take 1 damage, current HP: " + player.get(currentPlayer).getHealth());
                output = output + "Dynamite! Take 1 damage, current HP: " + player.get(currentPlayer).getHealth() + "\n";
                turn.checkPlayerDeath(player.get(currentPlayer)); //check since player took damage
                if(gameOver)
                {
                    //winCond = turn.winCondition();
                    return; //breakout since game is over
                }
            }
                
            if(player.get(currentPlayer).getCharacterName().equals("SUZY LAFAYETTE")) //add suzy ability, if no shoot dice at end of turn, plus 2 hp
            {
                //System.out.println("No shoot dice rolled, plus 2 HP");
                output = output + "No shoot dice rolled, plus 2 HP \n";
                if(diceHandler.checkFrequency("Shoot person one over left or right") == 0 
                        && diceHandler.checkFrequency("Shoot person two over left or right") == 0)
                    player.get(currentPlayer).addHealth(2);
            }

        }
        
        Dice dice = diceHandler.getDiceArray().get(diceCount);
        String diceString = dice.getDiceString();
        if(diceString.equals("Whiskey Bottle"))
        {
            turn.whiskey();
            if(name.equals("GREG DIGGER"))
                turn.whiskey();
        }
        else if(diceString.equals("Shoot person one over left or right"))
        {
            setShootValue(1);
            String shootOutput = "Pick who you would like to shoot based on dice";
            System.out.println("Please choose who you would like to shoot");
            WhoToShoot.setText(shootOutput);
            if(gameOver)
            {
                //winCond = turn.winCondition();
                return; //breakout since game is over
            }
        }
        else if(diceString.equals("Shoot person one over left or right twice"))
        {
            if(getAgain() == false) //used to make shooting happen twice, but still update the gui each time
                setAgain(true);
            else
                setAgain(false);
            setShootValue(1);
            String shootOutput = "Pick who you would like to shoot based on dice";
            System.out.println("Please choose who you would like to shoot");
            WhoToShoot.setText(shootOutput);
            if(gameOver)
            {
                //winCond = turn.winCondition();
                return; //breakout since game is over
            }
        }
        else if(diceString.equals("Shoot person two over left or right"))
        {
            setShootValue(2);
            String shootOutput = "Pick who you would like to shoot based on dice";
            System.out.println("Please choose who you would like to shoot");
            WhoToShoot.setText(shootOutput);
            if(gameOver)
            {
                //winCond = turn.winCondition();
                return; //breakout since game is over
            }
        }
        else if(diceString.equals("Shoot person two over left or right twice"))
        {
            if(getAgain() == false) //used to make shooting happen twice, but still update the gui each time
                setAgain(true);
            else
                setAgain(false);
            setShootValue(2);
            String shootOutput = "Pick who you would like to shoot based on dice";
            System.out.println("Please choose who you would like to shoot");
            WhoToShoot.setText(shootOutput);
            if(gameOver)
            {
                //winCond = turn.winCondition();
                return; //breakout since game is over
            }
        }
        else if(diceString.equals("Beer"))
        {
            String healOutput = "";
            System.out.println("Please choose who you would like to heal");
            for(int i = 0; i < tableSeating.size(); i++)
            {
                if(!(tableSeating.get(i).isFullHealth())) //if player not full HP, print them out
                {
                    healOutput = healOutput + "Player " + (i+1) + "  ";
                    //System.out.println(i + ": " + tableSeating.get(i).getCharacterName());
                }
            }
            WhoToHeal.setText(healOutput);
        }
        else if(diceString.equals("Double Beer"))
        {
            if(getAgain() == false) //used to make healing happen twice, but still update the gui each time
                setAgain(true);
            else
                setAgain(false);
            
            String healOutput = "";
            System.out.println("Please choose who you would like to heal");
            for(int i = 0; i < tableSeating.size(); i++)
            {
                if(!(tableSeating.get(i).isFullHealth())) //if player not full HP, print them out
                {
                    healOutput = healOutput + "Player " + (i+1) + "  ";
                    //System.out.println(i + ": " + tableSeating.get(i).getCharacterName());
                }
            }
            WhoToHeal.setText(healOutput);
        }
        
        if(diceCount == 4) //things to only do once, at the end
        {
            int gatlingTotal = diceHandler.checkFrequency("Gatling") + (2*diceHandler.checkFrequency("Double Gatling"));
            if(gatlingTotal >= 3)
            {
                turn.gatlingGun();
                if(gameOver)
                {
                    //winCond = turn.winCondition();
                    return; //breakout since game is over
                }
            }

            for(Dice d : diceHandler.getDiceArray()) //duel guns are resolved last
            {
                if(d.getDiceString().equals("Duel Guns"))
                {
                    String list = "";
                    int count = 1;
                    for(Player player1 : turn.getTableSeating())
                    {
                        if(!player1.equals(player.get(currentPlayer)))
                            list = list + count + ": " + player1.getCharacterName() + "\n";
                        count++;
                    }
                    DuelGUI obj1 = new DuelGUI(); //open a new duel gui
                    obj1.setNames(list);
                    obj1.setVisible(true);
                    obj1.setTableSeating(player);
                    //turn.duel();
                }
            }
        }
        
        increaseDiceCount();
       
        turn.tokens.addToken(player.get(currentPlayer).getTokenList());
        player.get(currentPlayer).wipeTokenList();
        setOutput(output);
        jTextArea1.setText(getOutput());
    }//GEN-LAST:event_ResolveActionPerformed

    private void ShootPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShootPersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShootPersonActionPerformed

    /**
     * Method that will allow the user to heal a player when the button is pressed.
     */
    private void healChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_healChoiceActionPerformed
        // TODO add your handling code here:
        //healing choice
        Turn turn = getTurn();
        int targetPlayer = (int)Float.parseFloat(HealPerson.getText());
        turn.beer(targetPlayer-1);
        setTurn(turn);
        
        WhoToHeal.setText("");
        
        if(getAgain())
            decreaseDiceCount(); //decrease the dicecount by one to repeat to heal to act as a pseudo double dice
    }//GEN-LAST:event_healChoiceActionPerformed

    /**
     * Method that will allow the user to shoot a player when the button is pressed.
     */
    private void ShootChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShootChoiceActionPerformed
        // TODO add your handling code here:
        //shooting choice
        Turn turn = getTurn();
        int targetPlayer = (int)Float.parseFloat(ShootPerson.getText());
        if(getShootValue() == 1) //value is the range of shooting
            turn.bullsEyex1(targetPlayer-1);
        else if(getShootValue() == 2)
            turn.bullsEyex2(targetPlayer-1);
        
        WhoToShoot.setText("");
        
        if(getAgain())
            decreaseDiceCount();  //decrease the dicecount by one to repeat to shoot to act as a pseudo double dice
    }//GEN-LAST:event_ShootChoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ArrowPile;
    private javax.swing.JTextField CardPile;
    private javax.swing.JTextField HealPerson;
    private javax.swing.JTextField IndianChiefArrow;
    private javax.swing.JButton NextTurn;
    private javax.swing.JTextField Player1Arrow;
    private javax.swing.JTextField Player1Char;
    private javax.swing.JTextField Player1Health;
    private javax.swing.JTextField Player1Roll;
    private javax.swing.JTextField Player1Zombie;
    private javax.swing.JTextField Player2Arrow;
    private javax.swing.JTextField Player2Char;
    private javax.swing.JTextField Player2Health;
    private javax.swing.JTextField Player2Roll;
    private javax.swing.JTextField Player2Zombie;
    private javax.swing.JTextField Player3Arrow;
    private javax.swing.JTextField Player3Char;
    private javax.swing.JTextField Player3Health;
    private javax.swing.JTextField Player3Roll;
    private javax.swing.JTextField Player3Zombie;
    private javax.swing.JTextField Player4Arrow;
    private javax.swing.JTextField Player4Char;
    private javax.swing.JTextField Player4Health;
    private javax.swing.JTextField Player4Roll;
    private javax.swing.JTextField Player4Zombie;
    private javax.swing.JTextField Player5Arrow;
    private javax.swing.JTextField Player5Char;
    private javax.swing.JTextField Player5Health;
    private javax.swing.JTextField Player5Roll;
    private javax.swing.JTextField Player5Zombie;
    private javax.swing.JTextField Player6Arrow;
    private javax.swing.JTextField Player6Char;
    private javax.swing.JTextField Player6Health;
    private javax.swing.JTextField Player6Roll;
    private javax.swing.JTextField Player6Zombie;
    private javax.swing.JTextField Player7Arrow;
    private javax.swing.JTextField Player7Char;
    private javax.swing.JTextField Player7Health;
    private javax.swing.JTextField Player7Roll;
    private javax.swing.JTextField Player7Zombie;
    private javax.swing.JTextField Player8Arrow;
    private javax.swing.JTextField Player8Char;
    private javax.swing.JTextField Player8Health;
    private javax.swing.JTextField Player8Roll;
    private javax.swing.JTextField Player8Zombie;
    private javax.swing.JButton Resolve;
    private javax.swing.JButton ShootChoice;
    private javax.swing.JTextField ShootPerson;
    private javax.swing.JButton Update;
    private javax.swing.JTextField WhoToHeal;
    private javax.swing.JTextField WhoToShoot;
    private javax.swing.JButton healChoice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
